### ISSUE TITLE
Result is null, unknown feng shui function

### ISSUE THREAD

**Issue by timshim** [fengshui-api/restApi#2]
Sorry for posting another issue so soon but I seem to be getting a result=null with status="Unknown feng shui function" in response to endpoint: https://fengshui-api.com/api/v1/findSignCompability?token=xxx&sign=7&sign2=3

**Comment by carriera** [comment]
Typo. findSignCompa**ti**bility

**Comment by timshim** [comment]
Ah sorry about that. My mistake. So I noticed the results are like '***' or '$$$'. Is this something like out of 5 stars? Will there be more information like a description of some sort?

**Comment by carriera** [comment]
In findLoveCompatibility and findBusinessCompatibility results are from 1 to 4.

Example of use findLoveCompatibility you can find at: http://wofs.com/index.php?option=com_jumi&fileid=8

**Comment by timshim** [comment]
Thanks for the info, though it seems I'm getting contradictory results from the API as compared to the wofs.com site. For eg. I'm using the endpoint findSignCompatibility with params sign=7, sign2=3. In the result, I'm seeing the description 'Worst couple', but on wofs.com I see 4/4 hearts for this match. Also, I seem to be getting a null for some matches from the API. Using the same endpoint above, if I use params sign=7, sign2= 2, the result gives me a null.

On a side note, are you able to use the title and description from the wofs.com site or is that a copyright issue? Would be nice to have more information in the response. :)

**Comment by carriera** [comment]
Firstly, thank you for reporting this null restart error. We appreciate your help.

Callculator "Sign Compatibility" is compatibile with descriptions from pages:
https://www.travelchinaguide.com/intro/social_customs/zodiac/compatibility.htm and http://www.chinahighlights.com/travelguide/chinese-zodiac/compatibility.htm

Calculator "Love Compatibility"  is compatibile with calculator from page http://wofs.com/index.php?option=com_jumi&fileid=8

When it comes to descriptions, it’s the best to use your own, like:

in "Love"
***\* There is a chance for a loving relationship with your partner.
**\* Most of the time it will be great but there might be differences between both of you
*\* You have to work it out in order to be happy
- There is little chance for you two and the relationship needs really hard work to keep the flame burning eternaly

in "Business"
***\* You and your partner are compatible and it will be easy to work together.
**\* Most of the time it will be ok but there will be differences for sure
*\* There might be ups and downs and you have to understandeach other because there might be misunderstandings which might lead to problems
- There is little chance that this partnership will be successful.
